[package]
name = "keeper-openapi"
version = "0.0.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
progenitor = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
