/*
 * Keeper API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
    #[serde(rename = "stderr", skip_serializing_if = "Option::is_none")]
    pub stderr: Option<String>,
    #[serde(rename = "stdout", skip_serializing_if = "Option::is_none")]
    pub stdout: Option<String>,
    #[serde(rename = "uuid")]
    pub uuid: String,
}

impl InlineObject {
    pub fn new(ok: bool, uuid: String) -> InlineObject {
        InlineObject {
            ok,
            status: None,
            stderr: None,
            stdout: None,
            uuid,
        }
    }
}


