/*
 * Keeper API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse201 {
    #[serde(rename = "existed_already")]
    pub existed_already: bool,
}

impl InlineResponse201 {
    pub fn new(existed_already: bool) -> InlineResponse201 {
        InlineResponse201 {
            existed_already,
        }
    }
}


