/*
 * Keeper API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputRecord {
    #[serde(rename = "msg")]
    pub msg: String,
    #[serde(rename = "stream")]
    pub stream: String,
    #[serde(rename = "time")]
    pub time: String,
}

impl OutputRecord {
    pub fn new(msg: String, stream: String, time: String) -> OutputRecord {
        OutputRecord {
            msg,
            stream,
            time,
        }
    }
}


