/*
 * Keeper API
 *
 * report execution of cron jobs through a mechanism other than mail
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportId {
    #[serde(rename = "host")]
    pub host: String,
    #[serde(rename = "job")]
    pub job: String,
    #[serde(rename = "pid")]
    pub pid: i32,
    #[serde(rename = "time")]
    pub time: String,
    #[serde(rename = "uuid")]
    pub uuid: String,
}

impl ReportId {
    pub fn new(host: String, job: String, pid: i32, time: String, uuid: String) -> ReportId {
        ReportId {
            host,
            job,
            pid,
            time,
            uuid,
        }
    }
}


