/*
 * Keeper API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportFinishBody {
    #[serde(rename = "duration_millis")]
    pub duration_millis: i32,
    #[serde(rename = "end_time")]
    pub end_time: String,
    #[serde(rename = "exit_status")]
    pub exit_status: i32,
    #[serde(rename = "id")]
    pub id: crate::models::ReportId,
}

impl ReportFinishBody {
    pub fn new(duration_millis: i32, end_time: String, exit_status: i32, id: crate::models::ReportId) -> ReportFinishBody {
        ReportFinishBody {
            duration_millis,
            end_time,
            exit_status,
            id,
        }
    }
}


