/*
 * Keeper API
 *
 * report execution of cron jobs through a mechanism other than mail
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportStartBody {
    #[serde(rename = "id")]
    pub id: crate::models::ReportId,
    #[serde(rename = "script")]
    pub script: String,
    #[serde(rename = "start_time")]
    pub start_time: String,
}

impl ReportStartBody {
    pub fn new(id: crate::models::ReportId, script: String, start_time: String) -> ReportStartBody {
        ReportStartBody {
            id,
            script,
            start_time,
        }
    }
}


