/*
 * Keeper API
 *
 * report execution of cron jobs through a mechanism other than mail
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportSummary {
    #[serde(rename = "age_seconds")]
    pub age_seconds: i32,
    #[serde(rename = "duration_seconds")]
    pub duration_seconds: i32,
    #[serde(rename = "host")]
    pub host: String,
    #[serde(rename = "job")]
    pub job: String,
    #[serde(rename = "status")]
    pub status: i32,
    #[serde(rename = "when")]
    pub when: String,
}

impl ReportSummary {
    pub fn new(age_seconds: i32, duration_seconds: i32, host: String, job: String, status: i32, when: String) -> ReportSummary {
        ReportSummary {
            age_seconds,
            duration_seconds,
            host,
            job,
            status,
            when,
        }
    }
}


