[package]
name = "keeper-common"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
